#  following a turoial on Building a workflow with GitHub Actions

name: hello-world
on: push # the push event runs your workflow when you push a commit or tag
jobs: 
  hello-world-job:
    runs-on: ubuntu-latest
    steps: 
      - name: Check out repository code
        uses: actions/checkout@v3
      - run: echo "$(cat hello_world.txt)"
